/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * append_log_entries.cc
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 14:00:23
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include "tinyrpc/comm/log.h"
#include "charon/interface/append_log_entries.h"
#include "charon/pb/charon.pb.h"

namespace charon {

AppendLogEntriesInterface::AppendLogEntriesInterface(const ::AppendLogEntriesRequest& request, ::AppendLogEntriesResponse& response)
  : m_request(request), 
  m_response(response) {

}

AppendLogEntriesInterface::~AppendLogEntriesInterface() {

}

void AppendLogEntriesInterface::run() {
  //
  // Run your business at here
  // m_reponse.set_ret_code(0);
  // m_reponse.set_res_info("Succ");
  //

}


}