/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * ask_vote.cc
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 14:00:23
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include "tinyrpc/comm/log.h"
#include "charon/interface/ask_vote.h"
#include "charon/pb/charon.pb.h"
#include "charon/raft/raft_node.h"

namespace charon {

AskVoteInterface::AskVoteInterface(const ::AskVoteRequest& request, ::AskVoteResponse& response)
  : m_request(request), 
  m_response(response) {

}

AskVoteInterface::~AskVoteInterface() {

}

void AskVoteInterface::run() {
  //
  // Run your business at here
  // m_reponse.set_ret_code(0);
  // m_reponse.set_res_info("Succ");
  //
  
  RaftNodeContainer::GetRaftNodeContainer()->getRaftNode(0)->handleAskVote(m_request, m_response);

}


}