/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * ask_vote.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 14:00:23
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef CHARON_INTERFACE_ASK_VOTE_H
#define CHARON_INTERFACE_ASK_VOTE_H 

#include "charon/pb/charon.pb.h"


namespace charon {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class AskVoteInterface {
 public:

  AskVoteInterface(const ::AskVoteRequest& request, ::AskVoteResponse& response);

  ~AskVoteInterface();

  void run();

 private:
  const ::AskVoteRequest& m_request;      // request object fron client

  ::AskVoteResponse& m_response;           // response object that reply to client

};


}


#endif