/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * discover_server.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 14:00:23
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef CHARON_INTERFACE_DISCOVER_SERVER_H
#define CHARON_INTERFACE_DISCOVER_SERVER_H 

#include "charon/pb/charon.pb.h"


namespace charon {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class DiscoverServerInterface {
 public:

  DiscoverServerInterface(const ::DiscoverRequest& request, ::DiscoverResponse& response);

  ~DiscoverServerInterface();

  void run();

 private:
  const ::DiscoverRequest& m_request;      // request object fron client

  ::DiscoverResponse& m_response;           // response object that reply to client

};


}


#endif