/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * query_all_raft_server_node.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-20 14:23:00
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef CHARON_INTERFACE_QUERY_ALL_RAFT_SERVER_NODE_H
#define CHARON_INTERFACE_QUERY_ALL_RAFT_SERVER_NODE_H 

#include "charon/pb/charon.pb.h"


namespace charon {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class QueryAllRaftServerNodeInterface {
 public:

  QueryAllRaftServerNodeInterface(const ::QueryAllRaftServerNodeRequest& request, ::QueryAllRaftServerNodeResponse& response);

  ~QueryAllRaftServerNodeInterface();

  void run();

  void checkInputParam();

  void setOutputParam();

  void queryAllRaftServer();

 private:
  const ::QueryAllRaftServerNodeRequest& m_request;      // request object fron client

  ::QueryAllRaftServerNodeResponse& m_response;           // response object that reply to client

};


}


#endif