/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * query_all_raft_server_node.cc
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-20 14:23:00
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include "tinyrpc/comm/log.h"
#include "charon/interface/query_all_raft_server_node.h"
#include "charon/pb/charon.pb.h"

namespace charon {

QueryAllRaftServerNodeInterface::QueryAllRaftServerNodeInterface(const ::QueryAllRaftServerNodeRequest& request, ::QueryAllRaftServerNodeResponse& response)
  : m_request(request), 
  m_response(response) {

}

QueryAllRaftServerNodeInterface::~QueryAllRaftServerNodeInterface() {

}

void QueryAllRaftServerNodeInterface::run() {
  //
  // Run your business at here
  // m_reponse.set_ret_code(0);
  // m_reponse.set_res_info("Succ");
  //

}


}