/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * run_charon.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 21:56:10
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/

#ifndef CHARON_INTERFACE_RUN_CHARON_H
#define CHARON_INTERFACE_RUN_CHARON_H 

#include "charon/pb/charon.pb.h"


namespace charon {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class RunCharonInterface {
 public:

  RunCharonInterface(const ::RunCharonRequest& request, ::RunCharonResponse& response);

  ~RunCharonInterface();

  void run();

  void checkInputParam();

  void handle();

  void handleRequestFromClient();

  void handleRequestFromRaftNode();

 private:
  const ::RunCharonRequest& m_request;      // request object fron client

  ::RunCharonResponse& m_response;           // response object that reply to client

  REQUEST_ORIGIN m_origin {EN_REQUEST_UNDEFINE};

};


}


#endif