/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * run_charon.cc
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 21:56:10
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include "tinyrpc/comm/log.h"
#include "charon/interface/run_charon.h"
#include "charon/pb/charon.pb.h"

namespace charon {

RunCharonInterface::RunCharonInterface(const ::RunCharonRequest& request, ::RunCharonResponse& response)
  : m_request(request), 
  m_response(response) {

}

RunCharonInterface::~RunCharonInterface() {

}

void RunCharonInterface::run() {
  //
  // Run your business at here
  // m_reponse.set_ret_code(0);
  // m_reponse.set_res_info("Succ");
  //

}


void RunCharonInterface::checkInputParam() {

}


}