/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * charon.h
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 14:00:23
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/


#include <google/protobuf/service.h>
#include "tinyrpc/comm/start.h"
#include "charon/service/charon.h"
#include "charon/raft/raft_node.h"


int main(int argc, char* argv[]) {
  if (argc != 2) {
    printf("Start charon server error, input argc is not 2!");
    printf("Start charon like this: \n");
    printf("./charon charon.xml\n");
    return 0;
  }

  tinyrpc::InitConfig(argv[1]);

  REGISTER_SERVICE(charon::CharonServiceImpl);

  auto cb = []() {
    charon::RaftNodeContainer::GetRaftNodeContainer()->getRaftNode(0)->resetElectionTimer();
  };
  tinyrpc::GetServer()->getIOThreadPool()->addCoroutineToEachThread(cb);


  tinyrpc::StartRpcServer();
  
  return 0;
}