/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * charon.cc
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-12-03 01:25:14
 * This file will be overwrite every time
*************************************************************/


#include <google/protobuf/service.h>
#include <exception>
#include "tinyrpc/comm/log.h"
#include "charon/pb/charon.pb.h"
#include "charon/service/charon.h"
#include "charon/comm/business_exception.h"
#include "charon/interface/discover_server.h"
#include "charon/interface/register_server.h"
#include "charon/interface/ask_vote.h"
#include "charon/interface/append_log_entries.h"
#include "charon/interface/operate_raft_server_node.h"
#include "charon/interface/query_all_raft_server_node.h"
#include "charon/interface/run_charon.h"


#define CALL_RPC_INTERFACE(type)                                                                                                    \
  type impl(*request, *response);                                                                                                   \
  try {                                                                                                                             \
    AppInfoLog << "request:{" << request->ShortDebugString() << "}";                                                                \
    impl.run();                                                                                                                     \
    response->set_ret_code(0);                                                                                                      \
    response->set_res_info("OK");                                                                                                   \
    AppInfoLog << "response:{" << response->ShortDebugString() << "}";                                                              \
  } catch (charon::BusinessException& e) {                                                                                 \
    AppErrorLog << "[" << e.file_name() << ":" << e.line() << "] occur BusinessException, error code = "                            \
      << e.code() << ", errinfo = " << e.error();                                                                                   \
    response->set_ret_code(e.code());                                                                                               \
    response->set_res_info(e.error());                                                                                              \
    AppInfoLog << "response:{" << response->ShortDebugString() << "}";                                                              \
  } catch (std::exception&) {                                                                                                       \
    AppErrorLog << "occur std::exception, error code = -1, errorinfo = UnKnown error ";                                             \
    response->set_ret_code(-1);                                                                                                     \
    response->set_res_info("UnKnown error");                                                                                        \
    AppInfoLog << "response:{" << response->ShortDebugString() << "}";                                                              \
  } catch (...) {                                                                                                                   \
    AppErrorLog << "occur UnKnown exception, error code = -1, errorinfo = UnKnown error ";                                          \
    response->set_ret_code(-1);                                                                                                     \
    response->set_res_info("UnKnown error");                                                                                        \
    AppInfoLog << "response:{" << response->ShortDebugString() << "}";                                                              \
  }                                                                                                                                 \
  if (done) {                                                                                                                       \
    done->Run();                                                                                                                    \
  }                                                                                                                                 \

namespace charon {

void CharonServiceImpl::DiscoverServer(::google::protobuf::RpcController* controller,
                       const ::DiscoverRequest* request,
                       ::DiscoverResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(DiscoverServerInterface);
}

void CharonServiceImpl::RegisterServer(::google::protobuf::RpcController* controller,
                       const ::RegisterRequest* request,
                       ::RegisterResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(RegisterServerInterface);
}

void CharonServiceImpl::AskVote(::google::protobuf::RpcController* controller,
                       const ::AskVoteRequest* request,
                       ::AskVoteResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(AskVoteInterface);
}

void CharonServiceImpl::AppendLogEntries(::google::protobuf::RpcController* controller,
                       const ::AppendLogEntriesRequest* request,
                       ::AppendLogEntriesResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(AppendLogEntriesInterface);
}

void CharonServiceImpl::OperateRaftServerNode(::google::protobuf::RpcController* controller,
                       const ::OperateRaftServerNodeRequest* request,
                       ::OperateRaftServerNodeResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(OperateRaftServerNodeInterface);
}

void CharonServiceImpl::QueryAllRaftServerNode(::google::protobuf::RpcController* controller,
                       const ::QueryAllRaftServerNodeRequest* request,
                       ::QueryAllRaftServerNodeResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(QueryAllRaftServerNodeInterface);
}

void CharonServiceImpl::RunCharon(::google::protobuf::RpcController* controller,
                       const ::RunCharonRequest* request,
                       ::RunCharonResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(RunCharonInterface);
}



}