/*************************************************************
** business_exception.cc
** Generated by tinyrpc framework tinyrpc_generator.py
** Create Time: 2022-11-13 14:00:23
*************************************************************/

#ifndef CHARON_COMM_BUSINESSEXCEPTION_H
#define CHARON_COMM_BUSINESSEXCEPTION_H 

/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * business_exception.cc
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2022-11-13 14:00:23
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
*************************************************************/




#include <exception>
#include <string>
#include <memory>
#include "tinyrpc/comm/log.h"


namespace charon {

class BusinessException : public std::exception {
 public:

  BusinessException(long long code, const std::string& err_info) {
    m_error_code = code;
    AppInfoLog << "throw CharonException: {code: " << m_error_code << ", errinfo:" << m_error_info << "}";
  }

  ~BusinessException() {
  
  }

  const char* what() {
    return m_error_info.c_str();
  }

  std::string error() {
    return m_error_info;
  }

  long long code() {
    return m_error_code;
  }

 private:
  long long m_error_code {0};
  std::string m_error_info;

};

}

#endif