#ifndef CHARON_COMM_ERRCODE_H
#define CHARON_COMM_ERRCODE_H

namespace charon {

const int ERROR_KEY_EMPTY = 100;
const int ERROR_SERVER_ADDR_EMPTY = 101;
const int ERROR_SERVER_ADDR_INVALID = 102;
const int ERROR_REGISTER_SERVER_ADDR_EMPTY = 103;
const int ERROR_REGISTER_SERVER_TAG_INVALID = 104;

const int ERROR_INVALID_THREAD_HASH = 105;


}


#endif